### ISSUE TITLE
[Error] "ELF could either not be parsed or written to!"

### ISSUE THREAD

**Issue by ThisNekoGuy** [flathub/io.github.Snaggly.PS2_Pnacher#2]
Is there something I'm doing wrong or is this not supposed to happen?
This is a proper dump of the game, so I don't understand why this is an issue. :/

![Screenshot_20220923_213005](https://user-images.githubusercontent.com/28468662/192076364-58d30158-b76e-490c-bde2-2f39536916c3.png)

**Comment by Snaggly** [comment]
Hello,
either Flatpak prevented you from opening a writing stream into your selected file or there was indeed trouble with parsing the ELF inside the ISO.

Can you test by giving the app access to the folder where your ISO file relies using Flatseal or CLI? Could you also tell me the GameID of that ISO you have? Is it maybe SLUS-21621?

**Comment by ThisNekoGuy** [comment]
> Can you test by giving the app access to the folder where your ISO file relies using Flatseal or CLI?

![Screenshot_20220925_164906](https://user-images.githubusercontent.com/28468662/192167083-064ed033-d12f-49d0-8a8c-881034fe4c8a.png)
`error: Key file contains key “filesystems” which has a value that cannot be interpreted.`

~~Not sure what it is I'm doing wrong here?~~

EDIT: Nevermind, it was the backslash Lol

> Could you also tell me the GameID of that ISO you have? Is it maybe SLUS-21621?

Yeah, it's `SLUS-21621`

**Comment by ThisNekoGuy** [comment]
It still fails, even when adding the paths by the way

**Comment by Snaggly** [comment]
Thanks, I suspect the Elf parser here fails for this game. I will check on it later when I get time again 👍

**Comment by Snaggly** [comment]
Found the source of this issue:
https://github.com/Snaggly/PS2_Pnacher/blob/main/src/mainapp.cpp#L25

I wrongly assumed the program would calculate in uint64_t, but apparently that is not the case. The calculation stays in 32bit and the result it taken to that variable. I'll fix it and once I figured out how to port this into GTK4. Thank you for reporting this bug!

**Comment by ThisNekoGuy** [comment]
Interesting; I'm not a C++ programmer, so I don't completely understand _how_ that line's doing what it is but no problem Lol
Thanks to you too :+1:

**Comment by Snaggly** [comment]
Hello again, 
sorry it took so long. I updated the app, you'll sooner or later receive the updated version with the fix applied.

I will close this issue for now. If you have more issues to report don't hesitate to reopen a new ticket, thanks!
